### ISSUE TITLE
Beta 2

### ISSUE THREAD

**Issue by bennuttall** [RPi-Distro/python-gpiozero#46]
Let's get a second beta out this week. Here's what's to be done:

- [x] #43 Mandatory pin on PWMOutputDevice?
- [x] #45 Change PWM interface from 0-100 to 0-1
- [x] #40 Change RGBLED interface from 0-100 to 0-255
- ~~#41 Decide on generic ADC interface and specific analogue interfaces like Potentiometer~~
- [x] Update docs accordingly
- [x] #47 Motor interface has inconsistent interface

**Comment by bennuttall** [comment]
Skipping #41 for now and do a release - let's have sorted in the next release.
